server:
  #  port: 1000
  #  port: 2000 集群注册
  port: 3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/ # 作为客户端访问注册中心访问的url
spring:
  application:
    name: atguigu-provoider # 为微服务工程设置一个应用名称,必须添加，以便以后客户端使用

management:
  endpoints:
    web:
      exposure:
        include:
          hystrix.stream,info,health
